### PR TITLE
Routing

### PR DESCRIPTION
**Pull request by Clifford2910**
updated front end to access distance and postcode as state. alert uses this state so we know it works

### CODE REVIEW

**Review by KOlofinmoyin — DISMISSED** [review]
:shipit: 👍

**Review by eliseaston — DISMISSED** [review]
Great job, definitely getting there! Thanks for explaining how React works.

**Review by ghost — APPROVED** [review]
Well Done!

**Review by KOlofinmoyin — APPROVED** [review]
:shipit: 👍

**Pull request merged**
